name: Create envfile

on: [pull_request, push]

jobs:

  create-envfile:
 
    runs-on: ubuntu-latest
 
    steps:
    - name: Make envfile
      uses: SpicyPizza/create-envfile@v1
      with:
        envkey_DEBUG: false
        envkey_SOME_API_KEY: "123456abcdef"
        envkey_GOOG_CLIENT_ID: ${{ secrets.GOOG_CLIENT_ID }}
        envkey_GOOG_CLIENT_SECRET: ${{ secrets.GOOG_CLIENT_SECRET }}
        directory: ClusterBank3TierCapstone/
        file_name: .env
